# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=20, default=49.99),
        ),
    ]
