# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20180325_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=49.99, max_digits=20),
        ),
    ]
