# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20180325_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
