# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.upload_image_path),
        ),
    ]
