# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marcado',
            field=models.SlugField(default='abc'),
            preserve_default=False,
        ),
    ]
