# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_auto_20180326_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marcado',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
