# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-20 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20180326_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
